### ISSUE TITLE
Recuperar valores en el DOM

### ISSUE THREAD

**Issue by acanivano** [acanivano/emprendedoresTarifa#1]
Hola @MundoGister 
Incorporé la parte del código que me dijiste en el issue que te puse #Problemas con Dom by ID y sigue dando los mismos problemas de null.
El caso que las lineas que me comentabas para que cargara todo el dom antes sí las tenía puesta.
He subido el código completo; no sé si podrías echarle un vistazo y comentarme a ver que está ocurriendo; seguro que es una parida o es que se me está olvidando cargar algo...

P.D. ¿Se puede referenciar en esta ventana a un issue de otro repositorio como por ejemplo el que te abrí el otro día?

**Comment by CarlosHerrera4** [comment]
Hola @acanivano 
Me he hecho un fork de tu repositorio y he hecho algunos cambios. Te he enviado un pull Request con los cambios que he hecho (puedes aceptarlos y se aplicarán directamente a tu código o simplemente tenerlo ahí para ver qué líneas he cambiado).
Investigando sobre el Select, he visto que da problemas con el evento "change" (no así con "click"), lo cual me parece raro. He visto un ejemplo que soluciona ese problema pero bajo mi opinión, es un poco lioso (aquí tienes el [enlace ](http://jsfiddle.net/phusick/Hp5jr/)por si quieres echarle un vistazo). Yo pasaría del `dijit/form/Select` y lo realizaría simplemente con el tag de HTML `select`. Luego podrás aplicarle el estilo que quieras.

**Comment by acanivano** [comment]
Hola @MundoGister . Gracias por tu ayuda, me está viniendo muy bien. Hice los cambios que me comentaste y he probado con varios eventos; "change" parece que me va bien ya que saca los resultados.
Lo que me pasa es que no dibuja la layer con el query puesto, salta un error en el inspector de Chrome

`dojo.io.script error Error: Failed to execute query.
    at Object.h.load (init.js:885)
    at init.js:191
    at c (init.js:76)
    at d (init.js:76)
    at b.Deferred.resolve.callback (init.js:77)
    at c (init.js:76)
    at d (init.js:76)
    at b.Deferred.resolve.callback (init.js:77)
    at init.js:1507
    at k (init.js:199)`

Hasta la parte de la feature funciona correctamente, es después cuando falla. ¿Es posible que, de alguna manera no se esté comunicando el query con el constructor de layers?
 `var localOSM = new FeatureLayer(localesOSM);
                localOSM.selectFeatures(query,FeatureLayer.SELECTION_NEW);`

¿No tendrá que ver que la query no se haga dentro de un map.on?

https://jsfiddle.net/btsfufms/
P.D. Muy buena página esta que me dijiste

**Comment by acanivano** [comment]
Vale, ya lo he conseguido. Me faltaba unas comillas en la query...Anda que.  Subiré el código de esta parte por si quieres echarle un vistazo.
El siguiente paso de la app es meterle un Service Area

**Comment by CarlosHerrera4** [comment]
Me alegro de que te ya te funcione correctamente. No puedo probarla ya que al tener las capas en tu server, yo no puedo verlas, pero no veo ningún problema a priori. Cualquier problema ya sabes :)
